{
 "title": "Kafka",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "kafka_cluster", "query": { "query": "label_values(kafka_cr)" } }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{kafka_cr=\"$kafka_cluster\"}[1m])) by (kafka_cr, brokerId)",
     "legendFormat": "{{kafka_cr}} - broker-{{brokerId}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{kafka_cr=\"$kafka_cluster\"}) by (kafka_cr, brokerId)",
     "legendFormat": "{{kafka_cr}} - broker-{{brokerId}}"
    }
   ]
  },
  {
   "title": "Broker Request Rate / sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg(sum (rate(kafka_network_requestmetrics_requests_total{kafka_cr=\"$kafka_cluster\"}[15m])) by(brokerId, kafka_cr, namespace)) by (kafka_cr, namespace)"
    }
   ]
  },
  {
   "title": "Broker Underreplicated",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions) by (kafka_cr, brokerId)",
     "legendFormat": "{{kafka_cr}} - broker-{{brokerId}}"
    }
   ]
  },
  {
   "title": "Partition Count",
   "type": "timeseries",
   "description": "Included partition of cruise control and offset",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount) by (kafka_cr, brokerId)",
     "legendFormat": "{{kafka_cr}} - broker-{{brokerId}}"
    }
   ]
  },
  { "title": "Message In/Out", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Topic Message In / sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka/$kafka_cluster-kafka\",topic!~\"^__.+\",topic!=\"\"}[5m])) by (kafka_cr, topic)",
     "legendFormat": "{{kafka_cr}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Topic Message In Size / sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka/$kafka_cluster-kafka\",topic!~\"^__.+\",topic!=\"\"}[5m])) by (kafka_cr, topic)",
     "legendFormat": "{{kafka_cr}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Topic Message Out Size / sec",
   "type": "timeseries",
   "description": "It can larger than message in. Because can have more than one consumer. Or consumer can read old message.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka/$kafka_cluster-kafka\",topic!~\"^__.+\",topic!=\"\"}[5m])) by (kafka_cr, topic)",
     "legendFormat": "{{kafka_cr}} - {{topic}}"
    }
   ]
  },
  { "title": "Disk Space", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Disk Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg((kubelet_volume_stats_capacity_bytes{job=\"kubelet\",metrics_path=\"/metrics\",namespace=~\".*\",persistentvolumeclaim=~\"$kafka_cluster-\\\\d+-storage-.*\"} - kubelet_volume_stats_available_bytes{job=\"kubelet\",metrics_path=\"/metrics\",namespace=~\".*\",persistentvolumeclaim=~\"$kafka_cluster-\\\\d+-storage-.*\"})/ kubelet_volume_stats_capacity_bytes{job=\"kubelet\",metrics_path=\"/metrics\",namespace=~\".*\",persistentvolumeclaim=~\"$kafka_cluster-\\\\d+-storage-.*\"}) by (persistentvolumeclaim)",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Predict Available Space",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(predict_linear(kubelet_volume_stats_available_bytes{job=\"kubelet\",metrics_path=\"/metrics\",namespace=~\".*\",persistentvolumeclaim=~\"$kafka_cluster-\\\\d+-storage-.*\"}[6h], 4 * 24 * 3600)) by (persistentvolumeclaim)",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}